#!/bin/bash

function dockerlint(){
    bash -x ~/.rcz/scripts/hadolint.sh $1
}

function get_container_scanning_tools(){

	echo anchore - gryp
	curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
	echo """
	SEE https://github.com/anchore/grype for more info
	"""
	grype


	echo Syft
	curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin
	echo """
	SEE https://github.com/anchore/syft
	"""

	syft
}
